server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql://121.43.100.25:3306/jfshop
    username: root
    password: Lh940228.
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  instance:
    lease-expiration-duration-in-seconds: 15 #过期时间
    lease-renewal-interval-in-seconds: 5 #心跳时间
mybatis:
  type-aliases-package: com.jfshop.item.pojo